Repository Dirtfy/PPP, pull requests merged in 2024-11, with the labels that each got.

#48 issue_#43-record-id
  app/src/main/java/com/dirtfy/ppp/common/exception/RecordException.kt
  app/src/main/java/com/dirtfy/ppp/data/api/RecordApi.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/common/firebase/FireStorePath.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/account/firebase/AccountFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/record/firebase/FireStoreRecord.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/record/firebase/RecordFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/dto/feature/record/DataRecord.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/TableBusinessLogic.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/common/converter/feature/record/RecordAtomConverter.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/record/atom/UiRecord.kt
Labels: enhancement

#57 Pay with Point 시 잔고 확인 후 잔액 부족 시 notice
  app/src/main/java/com/dirtfy/ppp/common/exception/TableException.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/TableBusinessLogic.kt
Labels: bug-fix

#62 TableViewModel 코드 분리
  app/src/main/java/com/dirtfy/ppp/common/di/AndroidViewModelModule.kt
  app/src/main/java/com/dirtfy/ppp/common/di/ControllerModule.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/TableMenuController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/TableMergeController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/TableOrderController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableMenuControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableMergeControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableOrderControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/table/UiTableMenuScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/table/UiTableMergeScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/table/UiTableOrderScreenState.kt
Labels: enhancement

#59 issue_#49
  app/src/main/java/com/dirtfy/ppp/data/api/AccountApi.kt
  app/src/main/java/com/dirtfy/ppp/data/api/RecordApi.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/account/firebase/AccountFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/account/firebase/FireStoreAccount.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/record/firebase/FireStoreRecord.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/record/firebase/RecordFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/dto/feature/account/DataAccount.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/AccountBusinessLogic.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/common/BusinessLogic.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/common/converter/RecordDataConverter.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/common/converter/feature/account/AccountAtomConverter.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/record/RecordScreen.kt
Labels: enhancement

#64 Integration of AccountControllers
  app/src/main/java/com/dirtfy/ppp/common/di/AndroidViewModelModule.kt
  app/src/main/java/com/dirtfy/ppp/common/di/ControllerModule.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountCreateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountListController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountUpdateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountCreateControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountDetailControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountListControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountUpdateControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/account/UiAccountCreateScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/account/UiAccountListScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/account/UiAccountScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountScreen.kt
Labels: enhancement

#70 fix issue 37
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountDetailScreen.kt
Labels: enhancement

#73 RecordControllers Reconstructed
  app/src/main/java/com/dirtfy/ppp/common/di/AndroidViewModelModule.kt
  app/src/main/java/com/dirtfy/ppp/common/di/ControllerModule.kt
  app/src/main/java/com/dirtfy/ppp/common/exception/RecordException.kt
  app/src/main/java/com/dirtfy/ppp/data/api/RecordApi.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/account/firebase/AccountFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/api/impl/feature/record/firebase/RecordFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/dto/feature/record/DataRecord.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/AccountBusinessLogic.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/RecordBusinessLogic.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/TableBusinessLogic.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/common/converter/feature/record/RecordAtomConverter.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountCreateControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountDetailControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountUpdateControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/RecordController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/RecordDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/RecordListController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordDetailControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordListControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/record/UiRecordDetailScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/record/UiRecordListScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/record/UiRecordScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/record/RecordDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/record/RecordScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/record/RecordDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/record/RecordScreen.kt
Labels: enhancement

#83 Loadingview from dw
  app/src/main/java/com/dirtfy/ppp/common/exception/ExceptionRetryHandling.kt
  app/src/main/java/com/dirtfy/ppp/common/exception/TableException.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountCreateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/AccountListController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountCreateControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountDetailControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountListControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountUpdateControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/menu/MenuController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/menu/MenuListController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/menu/MenuUpdateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/menu/impl/viewmodel/MenuListControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/menu/impl/viewmodel/MenuUpdateControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/menu/impl/viewmodel/MenuViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/RecordController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/RecordDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordDetailControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordListControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/TableController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/TableMenuController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/TableMergeController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/TableOrderController.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableMenuControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableMergeControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableOrderControllerImpl.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/common/UiScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/state/feature/record/UiRecordDetailScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/Component.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/menu/MenuScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/record/RecordDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/record/RecordScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/table/TableScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/menu/MenuScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/record/RecordDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/record/RecordScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/table/TableScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, bug-fix
