Repository Dirtfy/PPP, pull requests merged in 2024-10, with the labels that each got.

#22 dev-emit_flow_state
  app/src/main/java/com/dirtfy/ppp/data/logic/MenuService.kt
  app/src/main/java/com/dirtfy/ppp/data/source/firestore/menu/MenuFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/source/repository/MenuRepository.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/menu/UiMenu.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/menu/screen/UiMenuScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/MenuController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountUpdateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/MenuViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountCreateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountUpdateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/menu/MenuScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/menu/MenuScreen.kt
Labels: enhancement

#29 Dev dg
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/menu/MenuScreen.kt
Labels: bug

#25 .idea folder is ignored
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: cleaning

#28 Issue #11 #12 #13
  app/src/main/java/com/dirtfy/ppp/data/logic/AccountService.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/MenuService.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/RecordService.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/TableService.kt
  app/src/main/java/com/dirtfy/ppp/data/source/firestore/record/RecordFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/source/firestore/table/TableFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/source/repository/RecordRepository.kt
  app/src/main/java/com/dirtfy/ppp/data/source/repository/TableRepository.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/record/UiRecord.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/record/screen/UiRecordDetailScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/record/screen/UiRecordScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/table/UiPointUse.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/table/screen/UiTableScreenState.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountCreateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountUpdateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/record/RecordController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/record/RecordDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/table/TableController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountCreateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/record/RecordDetailViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/record/RecordViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/table/TableViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/record/RecordDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/record/RecordScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/table/TableOrderScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/table/TableScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/record/RecordDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/record/RecordScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/table/TableScreen.kt
Labels: enhancement

#31 dev-emit_flow_state
  app/src/main/java/com/dirtfy/ppp/common/FlowState.kt
  app/src/main/java/com/dirtfy/ppp/common/di/UiModule.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/Service.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/account/screen/UiAccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/MenuController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountCreateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountUpdateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/common/Controller.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/record/RecordController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/record/RecordDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/table/TableController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/table/TableOrderController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/MenuViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountCreateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountDetailViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountUpdateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/record/RecordDetailViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/record/RecordViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/record/ViewModelRecord.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/table/TableOrderViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/table/TableViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/menu/MenuScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/phone/table/TableOrderScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/menu/MenuScreen.kt
Labels: enhancement

#33 [Issue #18] error handling in controller, service, repository
  app/src/main/java/com/dirtfy/ppp/data/logic/MenuService.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/RecordService.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/Service.kt
  app/src/main/java/com/dirtfy/ppp/data/logic/TableService.kt
  app/src/main/java/com/dirtfy/ppp/data/source/firestore/account/AccountFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/source/firestore/menu/MenuFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/source/firestore/record/RecordFireStore.kt
  app/src/main/java/com/dirtfy/ppp/data/source/firestore/table/TableFireStore.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/table/UiTable.kt
  app/src/main/java/com/dirtfy/ppp/ui/dto/table/UiTableOrder.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/MenuController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountCreateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/account/AccountUpdateController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/record/RecordController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/record/RecordDetailController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/controller/table/TableController.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/MenuViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountCreateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountDetailViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/account/AccountUpdateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/record/RecordDetailViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/record/RecordViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/presenter/viewmodel/table/TableViewModel.kt
Labels: enhancement

#38 issue_#8-DI
  app/src/main/java/com/dirtfy/ppp/common/di/DataModule.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountCreateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountDetailViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountUpdateViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/account/impl/viewmodel/AccountViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/menu/impl/viewmodel/MenuViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordDetailViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/record/impl/viewmodel/RecordViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/controller/feature/table/impl/viewmodel/TableViewModel.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/MainActivity.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/TabletScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountCreateScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/account/AccountScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/menu/MenuScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/record/RecordDetailScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/record/RecordScreen.kt
  app/src/main/java/com/dirtfy/ppp/ui/view/tablet/table/TableScreen.kt
Labels: enhancement
